### PR TITLE
Build alpine corretto images for arm

### PR DESCRIPTION
**Pull request by bobziuchkovski**
We run jetty in production on amd64 containers. However, many of our engineers use Apple Silicon Macs for local development. This means running arm64 docker images locally instead of amd64.

We're trying to build as many of our containers as possible from alpine variants, but unfortunately the published jetty alpine corretto images are only available for amd64. Is there an intentional reason for that? I've submitted this PR in the hopes of enabling arm64 builds for those jetty alpine variants.

I confirmed each of the upstream corretto alpine images have published arm64 builds:

Screenshot 2023-09-27 at 10 03 15 AM

Screenshot 2023-09-27 at 10 03 49 AM

Screenshot 2023-09-27 at 10 04 38 AM

CC @shawncatz for visibility on our end

### CODE REVIEW

**Comment by bobziuchkovski** [comment]
I've signed the ECA and used the web UI to revalidate, but the check remains red. I'm not sure how to update it. However, here's proof of the signature:

Screenshot 2023-09-27 at 10 31 36 AM

**Comment by bobziuchkovski** [comment]
Hmm...I see the ECA status is now ✅ but the build failed. I'll take a look at the failure and try to update this PR.

**Comment by lachlan-roberts** [comment]
Yep looks like all the amazoncorretto images support arm64v8 so I think this is fine.

**Comment by lachlan-roberts** [comment]
The build failed on eclipse-temurin/11.0/jre11-alpine which you didn't even change. 

We have had some CI issues with this recently so maybe this is related, I will investigate.

**Comment by bobziuchkovski** [comment]
> The build failed on eclipse-temurin/11.0/jre11-alpine which you didn't even change.
> 
> We have had some CI issues with this recently so maybe this is related, I will investigate.

Thanks @lachlan-roberts ! I took a quick look on my end before realizing it was unrelated to my changes. Seems the error is `rm: can't remove '/jetty-keys/S.gpg-agent.extra': No such file or directory`. I poked at this locally and that file is a socket used by the gpg-agent. The gpg-agent process auto-spawns when the gpg cli commands are used to import keys.

I'm not 100% familiar with any of this, but explicitly killing the gpg-agent process before removing that /jetty-keys directory _might_ help resolve flakes there. Something like `gpgconf --kill gpg-agent` or an explicit kill/pkill statement.

Anyway, I don't mean to poke my nose into things, but that's what I discovered while looking into it for this PR. 😄

**Pull request merged**
