### PR TITLE
Update Jetty to 11.0.14, 10.0.14 and 9.4.51.v20230217

### PR DESCRIPTION
**Pull request by NotMyFault**
Like the title says, this PR adapts the latest Jetty release.

### CODE REVIEW

**Comment by olamy** [comment]
@NotMyFault thanks for your contribution. 
Did you sign the Eclipse ECA with same email as your commit? https://www.eclipse.org/legal/ECA.php

**Comment by NotMyFault** [comment]
> Did you sign the Eclipse ECA with same email as your commit? https://www.eclipse.org/legal/ECA.php

Yes, the email address on the DCO matches the email address I signed this commit off.

**Comment by NotMyFault** [comment]
> Did you sign the Eclipse ECA with same email as your commit? https://www.eclipse.org/legal/ECA.php

> Did you sign the Eclipse ECA with same email as your commit? https://www.eclipse.org/legal/ECA.php

Yes, the email address on the DCO matches the email address I signed this commit off.

Although it's green by now, no idea what changed.

**Comment by olamy** [comment]
@NotMyFault I have re asked the eca validation ;) (sometimes this eclipse service might be flaky or you have registered your eca very recently and there is maybe some caching)

**Review by olamy — APPROVED** [review]

**Comment by olamy** [comment]
lgtm

**Review by lachlan-roberts — APPROVED** [review]
Looks good, but doesn't look like you ran update.sh to do this because the GPG keys did not also update.

I will merge anyway and do that in a separate commit. Then do the release.

**Pull request merged**
