### PR TITLE
Restructure project to add support for additional base images.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Issue #14 & #63

- Restructure the project to use directory trees starting with the base image, in the format `$BASE_IMAGE/$JETTY_VERSION/$JDK_VERSION-$VARIANT`.
- Add support for eclipse-temurin and amazoncorretto images with alpine variants.
- Fix the `generate-stackbrew-library.sh` script so that tags can be generated for multiple base images.
- Add multiple new variants of the baseDockerfile that are selected in `update.sh` based on baseImage and the imageTag.

There are a lot of files changed but the main things changed to review are:
- The tags generated `by generate-stackbrew-library.sh`.
- The baseDockerfile and its variants.
  - baseDockerfile
  - baseDockerfile-alpine
  - baseDockerfile-amazoncorretto
  - baseDockerfile-slim
- update.sh

New Project Layout:
```
.
├── amazoncorretto
│   ├── 10.0
│   │   ├── jdk11
│   │   ├── jdk11-alpine
│   │   ├── jdk17
│   │   └── jdk17-alpine
│   ├── 11.0
│   │   ├── jdk11
│   │   ├── jdk11-alpine
│   │   ├── jdk17
│   │   └── jdk17-alpine
│   └── 9.4
│       ├── jdk11
│       ├── jdk11-alpine
│       ├── jdk17
│       ├── jdk17-alpine
│       ├── jdk8
│       └── jdk8-alpine
├── eclipse-temurin
│   ├── 10.0
│   │   ├── jdk11
│   │   ├── jdk11-alpine
│   │   ├── jdk17
│   │   └── jdk17-alpine
│   ├── 11.0
│   │   ├── jdk11
│   │   ├── jdk11-alpine
│   │   ├── jdk17
│   │   └── jdk17-alpine
│   └── 9.4
│       ├── jdk11
│       ├── jdk11-alpine
│       ├── jdk17
│       ├── jdk17-alpine
│       └── jdk8
├── openjdk
│   ├── 10.0
│   │   ├── jdk11
│   │   ├── jdk11-slim
│   │   ├── jdk17
│   │   ├── jdk17-slim
│   │   ├── jre11
│   │   └── jre11-slim
│   ├── 11.0
│   │   ├── jdk11
│   │   ├── jdk11-slim
│   │   ├── jdk17
│   │   ├── jdk17-slim
│   │   ├── jre11
│   │   └── jre11-slim
│   ├── 9.2
│   │   └── jre8
│   ├── 9.3
│   │   └── jre8
│   └── 9.4
│       ├── jdk11
│       ├── jdk11-slim
│       ├── jdk17
│       ├── jdk17-slim
│       ├── jdk8
│       ├── jdk-8-slim
│       ├── jre11
│       ├── jre11-slim
│       ├── jre8
│       └── jre8-slim
```

Output of `generate-stackbrew-library.sh`:
```
Maintainers: Greg Wilkins <gregw@webtide.com> (@gregw),
             Lachlan Roberts <lachlan@webtide.com> (@lachlan-roberts),
             Olivier Lamy <olamy@webtide.com> (@olamy),
             Joakim Erdfelt <joakim@webtide.com> (@joakime)
GitRepo: https://github.com/eclipse/jetty.docker.git

Tags: 9.4.44-jre8-slim, 9.4-jre8-slim, 9-jre8-slim, 9.4.44-jre8-slim-openjdk, 9.4-jre8-slim-openjdk, 9-jre8-slim-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/9.4/jre8-slim
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.4.44-jre8, 9.4-jre8, 9-jre8, 9.4.44-jre8-openjdk, 9.4-jre8-openjdk, 9-jre8-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/9.4/jre8
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.4.44-jre11-slim, 9.4-jre11-slim, 9-jre11-slim, 9.4.44-jre11-slim-openjdk, 9.4-jre11-slim-openjdk, 9-jre11-slim-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/9.4/jre11-slim
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.4.44-jre11, 9.4-jre11, 9-jre11, 9.4.44-jre11-openjdk, 9.4-jre11-openjdk, 9-jre11-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/9.4/jre11
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.4.44-jdk-8-slim, 9.4-jdk-8-slim, 9-jdk-8-slim, 9.4.44-jdk-8-slim-openjdk, 9.4-jdk-8-slim-openjdk, 9-jdk-8-slim-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/9.4/jdk-8-slim
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.4.44-jdk8, 9.4-jdk8, 9-jdk8, 9.4.44-jdk8-openjdk, 9.4-jdk8-openjdk, 9-jdk8-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/9.4/jdk8
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.4.44-jdk17-slim, 9.4-jdk17-slim, 9-jdk17-slim, 9.4.44-jdk17-slim-openjdk, 9.4-jdk17-slim-openjdk, 9-jdk17-slim-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/9.4/jdk17-slim
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.4.44, 9.4, 9, 9.4.44-jdk17, 9.4-jdk17, 9-jdk17, 9.4.44-openjdk, 9.4-openjdk, 9-openjdk, 9.4.44-jdk17-openjdk, 9.4-jdk17-openjdk, 9-jdk17-openjdk, latest, jdk17
Architectures: amd64, arm64v8
Directory: openjdk/9.4/jdk17
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.4.44-jdk11-slim, 9.4-jdk11-slim, 9-jdk11-slim, 9.4.44-jdk11-slim-openjdk, 9.4-jdk11-slim-openjdk, 9-jdk11-slim-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/9.4/jdk11-slim
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.4.44-jdk11, 9.4-jdk11, 9-jdk11, 9.4.44-jdk11-openjdk, 9.4-jdk11-openjdk, 9-jdk11-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/9.4/jdk11
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.3.30-jre8, 9.3-jre8, 9.3.30-jre8-openjdk, 9.3-jre8-openjdk, 9.3
Architectures: amd64, arm64v8
Directory: openjdk/9.3/jre8
GitCommit: bd5eabf5fcd22aa849773576b0ccc5457121bf75

Tags: 9.2.30-jre8, 9.2-jre8, 9.2.30-jre8-openjdk, 9.2-jre8-openjdk, 9.2
Architectures: amd64, arm64v8
Directory: openjdk/9.2/jre8
GitCommit: bd5eabf5fcd22aa849773576b0ccc5457121bf75

Tags: 11.0.7-jre11-slim, 11.0-jre11-slim, 11-jre11-slim, 11.0.7-jre11-slim-openjdk, 11.0-jre11-slim-openjdk, 11-jre11-slim-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/11.0/jre11-slim
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 11.0.7-jre11, 11.0-jre11, 11-jre11, 11.0.7-jre11-openjdk, 11.0-jre11-openjdk, 11-jre11-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/11.0/jre11
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 11.0.7-jdk17-slim, 11.0-jdk17-slim, 11-jdk17-slim, 11.0.7-jdk17-slim-openjdk, 11.0-jdk17-slim-openjdk, 11-jdk17-slim-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/11.0/jdk17-slim
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 11.0.7, 11.0, 11, 11.0.7-jdk17, 11.0-jdk17, 11-jdk17, 11.0.7-openjdk, 11.0-openjdk, 11-openjdk, 11.0.7-jdk17-openjdk, 11.0-jdk17-openjdk, 11-jdk17-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/11.0/jdk17
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 11.0.7-jdk11-slim, 11.0-jdk11-slim, 11-jdk11-slim, 11.0.7-jdk11-slim-openjdk, 11.0-jdk11-slim-openjdk, 11-jdk11-slim-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/11.0/jdk11-slim
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 11.0.7-jdk11, 11.0-jdk11, 11-jdk11, 11.0.7-jdk11-openjdk, 11.0-jdk11-openjdk, 11-jdk11-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/11.0/jdk11
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 10.0.7-jre11-slim, 10.0-jre11-slim, 10-jre11-slim, 10.0.7-jre11-slim-openjdk, 10.0-jre11-slim-openjdk, 10-jre11-slim-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/10.0/jre11-slim
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 10.0.7-jre11, 10.0-jre11, 10-jre11, 10.0.7-jre11-openjdk, 10.0-jre11-openjdk, 10-jre11-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/10.0/jre11
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 10.0.7-jdk17-slim, 10.0-jdk17-slim, 10-jdk17-slim, 10.0.7-jdk17-slim-openjdk, 10.0-jdk17-slim-openjdk, 10-jdk17-slim-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/10.0/jdk17-slim
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 10.0.7, 10.0, 10, 10.0.7-jdk17, 10.0-jdk17, 10-jdk17, 10.0.7-openjdk, 10.0-openjdk, 10-openjdk, 10.0.7-jdk17-openjdk, 10.0-jdk17-openjdk, 10-jdk17-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/10.0/jdk17
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 10.0.7-jdk11-slim, 10.0-jdk11-slim, 10-jdk11-slim, 10.0.7-jdk11-slim-openjdk, 10.0-jdk11-slim-openjdk, 10-jdk11-slim-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/10.0/jdk11-slim
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 10.0.7-jdk11, 10.0-jdk11, 10-jdk11, 10.0.7-jdk11-openjdk, 10.0-jdk11-openjdk, 10-jdk11-openjdk
Architectures: amd64, arm64v8
Directory: openjdk/10.0/jdk11
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.4.44-jdk8-eclipse-temurin, 9.4-jdk8-eclipse-temurin, 9-jdk8-eclipse-temurin
Architectures: amd64, arm64v8
Directory: eclipse-temurin/9.4/jdk8
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.4.44-jdk17-alpine-eclipse-temurin, 9.4-jdk17-alpine-eclipse-temurin, 9-jdk17-alpine-eclipse-temurin
Architectures: amd64, arm64v8
Directory: eclipse-temurin/9.4/jdk17-alpine
GitCommit: 41b92c3a61fb3eaa613b09f69efbbc8678e46862

Tags: 9.4.44-eclipse-temurin, 9.4-eclipse-temurin, 9-eclipse-temurin, 9.4.44-jdk17-eclipse-temurin, 9.4-jdk17-eclipse-temurin, 9-jdk17-eclipse-temurin
Architectures: amd64, arm64v8
Directory: eclipse-temurin/9.4/jdk17
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.4.44-jdk11-alpine-eclipse-temurin, 9.4-jdk11-alpine-eclipse-temurin, 9-jdk11-alpine-eclipse-temurin
Architectures: amd64, arm64v8
Directory: eclipse-temurin/9.4/jdk11-alpine
GitCommit: 41b92c3a61fb3eaa613b09f69efbbc8678e46862

Tags: 9.4.44-jdk11-eclipse-temurin, 9.4-jdk11-eclipse-temurin, 9-jdk11-eclipse-temurin
Architectures: amd64, arm64v8
Directory: eclipse-temurin/9.4/jdk11
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 11.0.7-jdk17-alpine-eclipse-temurin, 11.0-jdk17-alpine-eclipse-temurin, 11-jdk17-alpine-eclipse-temurin
Architectures: amd64, arm64v8
Directory: eclipse-temurin/11.0/jdk17-alpine
GitCommit: 41b92c3a61fb3eaa613b09f69efbbc8678e46862

Tags: 11.0.7-eclipse-temurin, 11.0-eclipse-temurin, 11-eclipse-temurin, 11.0.7-jdk17-eclipse-temurin, 11.0-jdk17-eclipse-temurin, 11-jdk17-eclipse-temurin
Architectures: amd64, arm64v8
Directory: eclipse-temurin/11.0/jdk17
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 11.0.7-jdk11-alpine-eclipse-temurin, 11.0-jdk11-alpine-eclipse-temurin, 11-jdk11-alpine-eclipse-temurin
Architectures: amd64, arm64v8
Directory: eclipse-temurin/11.0/jdk11-alpine
GitCommit: 41b92c3a61fb3eaa613b09f69efbbc8678e46862

Tags: 11.0.7-jdk11-eclipse-temurin, 11.0-jdk11-eclipse-temurin, 11-jdk11-eclipse-temurin
Architectures: amd64, arm64v8
Directory: eclipse-temurin/11.0/jdk11
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 10.0.7-jdk17-alpine-eclipse-temurin, 10.0-jdk17-alpine-eclipse-temurin, 10-jdk17-alpine-eclipse-temurin
Architectures: amd64, arm64v8
Directory: eclipse-temurin/10.0/jdk17-alpine
GitCommit: 41b92c3a61fb3eaa613b09f69efbbc8678e46862

Tags: 10.0.7-eclipse-temurin, 10.0-eclipse-temurin, 10-eclipse-temurin, 10.0.7-jdk17-eclipse-temurin, 10.0-jdk17-eclipse-temurin, 10-jdk17-eclipse-temurin
Architectures: amd64, arm64v8
Directory: eclipse-temurin/10.0/jdk17
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 10.0.7-jdk11-alpine-eclipse-temurin, 10.0-jdk11-alpine-eclipse-temurin, 10-jdk11-alpine-eclipse-temurin
Architectures: amd64, arm64v8
Directory: eclipse-temurin/10.0/jdk11-alpine
GitCommit: 41b92c3a61fb3eaa613b09f69efbbc8678e46862

Tags: 10.0.7-jdk11-eclipse-temurin, 10.0-jdk11-eclipse-temurin, 10-jdk11-eclipse-temurin
Architectures: amd64, arm64v8
Directory: eclipse-temurin/10.0/jdk11
GitCommit: 129bab37febf6520f10df1160845890f81f96535

Tags: 9.4.44-jdk8-alpine-amazoncorretto, 9.4-jdk8-alpine-amazoncorretto, 9-jdk8-alpine-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/9.4/jdk8-alpine
GitCommit: 41b92c3a61fb3eaa613b09f69efbbc8678e46862

Tags: 9.4.44-jdk8-amazoncorretto, 9.4-jdk8-amazoncorretto, 9-jdk8-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/9.4/jdk8
GitCommit: c832325e87147ef8ad3da1abbeaef6234d197bcb

Tags: 9.4.44-jdk17-alpine-amazoncorretto, 9.4-jdk17-alpine-amazoncorretto, 9-jdk17-alpine-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/9.4/jdk17-alpine
GitCommit: 41b92c3a61fb3eaa613b09f69efbbc8678e46862

Tags: 9.4.44-amazoncorretto, 9.4-amazoncorretto, 9-amazoncorretto, 9.4.44-jdk17-amazoncorretto, 9.4-jdk17-amazoncorretto, 9-jdk17-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/9.4/jdk17
GitCommit: c832325e87147ef8ad3da1abbeaef6234d197bcb

Tags: 9.4.44-jdk11-alpine-amazoncorretto, 9.4-jdk11-alpine-amazoncorretto, 9-jdk11-alpine-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/9.4/jdk11-alpine
GitCommit: 41b92c3a61fb3eaa613b09f69efbbc8678e46862

Tags: 9.4.44-jdk11-amazoncorretto, 9.4-jdk11-amazoncorretto, 9-jdk11-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/9.4/jdk11
GitCommit: c832325e87147ef8ad3da1abbeaef6234d197bcb

Tags: 11.0.7-jdk17-alpine-amazoncorretto, 11.0-jdk17-alpine-amazoncorretto, 11-jdk17-alpine-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/11.0/jdk17-alpine
GitCommit: 41b92c3a61fb3eaa613b09f69efbbc8678e46862

Tags: 11.0.7-amazoncorretto, 11.0-amazoncorretto, 11-amazoncorretto, 11.0.7-jdk17-amazoncorretto, 11.0-jdk17-amazoncorretto, 11-jdk17-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/11.0/jdk17
GitCommit: c832325e87147ef8ad3da1abbeaef6234d197bcb

Tags: 11.0.7-jdk11-alpine-amazoncorretto, 11.0-jdk11-alpine-amazoncorretto, 11-jdk11-alpine-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/11.0/jdk11-alpine
GitCommit: 41b92c3a61fb3eaa613b09f69efbbc8678e46862

Tags: 11.0.7-jdk11-amazoncorretto, 11.0-jdk11-amazoncorretto, 11-jdk11-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/11.0/jdk11
GitCommit: c832325e87147ef8ad3da1abbeaef6234d197bcb

Tags: 10.0.7-jdk17-alpine-amazoncorretto, 10.0-jdk17-alpine-amazoncorretto, 10-jdk17-alpine-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/10.0/jdk17-alpine
GitCommit: 41b92c3a61fb3eaa613b09f69efbbc8678e46862

Tags: 10.0.7-amazoncorretto, 10.0-amazoncorretto, 10-amazoncorretto, 10.0.7-jdk17-amazoncorretto, 10.0-jdk17-amazoncorretto, 10-jdk17-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/10.0/jdk17
GitCommit: c832325e87147ef8ad3da1abbeaef6234d197bcb

Tags: 10.0.7-jdk11-alpine-amazoncorretto, 10.0-jdk11-alpine-amazoncorretto, 10-jdk11-alpine-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/10.0/jdk11-alpine
GitCommit: 41b92c3a61fb3eaa613b09f69efbbc8678e46862

Tags: 10.0.7-jdk11-amazoncorretto, 10.0-jdk11-amazoncorretto, 10-jdk11-amazoncorretto
Architectures: amd64, arm64v8
Directory: amazoncorretto/10.0/jdk11
GitCommit: c832325e87147ef8ad3da1abbeaef6234d197bcb
```

### CODE REVIEW

**Comment by lachlan-roberts** [comment]
@tianon can you please take a look these changes to make sure we're not going down the wrong path.

We have had multiple requests to support additional base images other than openjdk. This PR adds support for eclipse-temurin and amazoncorretto, and more could be added in the future.

The concerning part about this PR is that it takes our total number of images from 24 to around 50. This could further increase if other base images are supported in the future.

Is there any concern from your side of us increasing the number of images we provide, or is this the standard?

**Comment by tianon** [comment]
I would say this is kind of a "known issue" in the Java ecosystem in general.  We definitely have issues with large numbers of supported variants, and the `tomcat` image is a pretty extreme example of this and just how horrid it makes the end-user experience: https://hub.docker.com/_/tomcat (https://github.com/docker-library/docs/blob/master/tomcat/README.md#supported-tags-and-respective-dockerfile-links)

**Comment by tianon** [comment]
To put that another way, we 100% regret opening this "pandora's box" in the `tomcat` image, and would not do so again if we could turn back the clock and do it over again.

I don't think I have any _great_ suggestions for alternatives, but I think an OK one would be to document how users can accomplish this themselves (perhaps something clever with `COPY --from=jetty:xxx` ?)

**Review by gregw — APPROVED** [review]
Whilst I too don't like this "pandora's box", I don't think we should stay outside the box whilst waiting for a better solution (or taking on the task of developing a better solution).

So I think we should go ahead with this restructure now and then look to see if there is something we can do to provide a process to make almost any base image into a jetty image.

**Review by joakime — APPROVED** [review]
It's a big change, I couldn't find anything specific to worry about.

**Comment by YTN01** [comment]
@lachlan-roberts Thanks for implementing this. Any chance of including Azul Zulu?

**Comment by joakime** [comment]
Should `amazoncorretto` be `amazon-corretto` (with the dash to conform to `eclipse-temurin`?)

If you add `azul-zulu` that would be another base (with a dash)

**Comment by lachlan-roberts** [comment]
> Should amazoncorretto be amazon-corretto (with the dash to conform to eclipse-temurin?)

@joakime no, the reason `amazoncorretto` does not have the dash is because it does not have the dash on DockerHub https://hub.docker.com/_/amazoncorretto, `eclipse-temurin` does have the dash on DockerHub.

Just simplifies things to have the tag and directory exactly the same as the base image name.

**Comment by lachlan-roberts** [comment]
> Any chance of including Azul Zulu?

@YTN01 yep, I will look at this after this PR is merged.

I'm planning to merge this after we release 9.4.45 and 10/11.0.8.

**Review by joakime — APPROVED** [review]

**Pull request merged**
